package com.techieblossom.kfcm.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFA33E0D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBCE)
val md_theme_light_onPrimaryContainer = Color(0xFF370E00)
val md_theme_light_secondary = Color(0xFF006970)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF7EF4FF)
val md_theme_light_onSecondaryContainer = Color(0xFF002022)
val md_theme_light_tertiary = Color(0xFF00696E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF6FF6FF)
val md_theme_light_onTertiaryContainer = Color(0xFF002022)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A18)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A18)
val md_theme_light_surfaceVariant = Color(0xFFF5DED6)
val md_theme_light_onSurfaceVariant = Color(0xFF53433E)
val md_theme_light_outline = Color(0xFF85736D)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEEA)
val md_theme_light_inverseSurface = Color(0xFF362F2C)
val md_theme_light_inversePrimary = Color(0xFFFFB599)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFA33E0D)
val md_theme_light_outlineVariant = Color(0xFFD8C2BB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB599)
val md_theme_dark_onPrimary = Color(0xFF5A1C00)
val md_theme_dark_primaryContainer = Color(0xFF7F2B00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBCE)
val md_theme_dark_secondary = Color(0xFF4DD9E5)
val md_theme_dark_onSecondary = Color(0xFF00363B)
val md_theme_dark_secondaryContainer = Color(0xFF004F55)
val md_theme_dark_onSecondaryContainer = Color(0xFF7EF4FF)
val md_theme_dark_tertiary = Color(0xFF4CD9E2)
val md_theme_dark_onTertiary = Color(0xFF00373A)
val md_theme_dark_tertiaryContainer = Color(0xFF004F53)
val md_theme_dark_onTertiaryContainer = Color(0xFF6FF6FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A18)
val md_theme_dark_onBackground = Color(0xFFEDE0DC)
val md_theme_dark_surface = Color(0xFF201A18)
val md_theme_dark_onSurface = Color(0xFFEDE0DC)
val md_theme_dark_surfaceVariant = Color(0xFF53433E)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BB)
val md_theme_dark_outline = Color(0xFFA08D86)
val md_theme_dark_inverseOnSurface = Color(0xFF201A18)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DC)
val md_theme_dark_inversePrimary = Color(0xFFA33E0D)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB599)
val md_theme_dark_outlineVariant = Color(0xFF53433E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFA6400F)


val rating5 = Color(0xFF0C8539)
val rating4 = Color(0xFF66A80F)
val rating3 = Color(0xFFE6B600)
val rating2 = Color(0xFFD95C0F)
val rating1 = Color(0xFFC92A2A)

//val groundColor = Color(0xFF006400)
val groundColor = Color(0xFF00563F)
val stripColor = Color(0x11D3F7D3)
val groundMarkingColor = Color(0x11CCCCCC)